# Generated by Django 4.0.1 on 2022-02-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default=None, max_length=100, null=True)),
                ('subcategory_name', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('hosting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('max_days_refund', models.IntegerField(default=None, null=True)),
                ('hosting_start_date', models.DateField(default=None, null=True)),
                ('published', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hosting.hosting')),
                ('per_night_cost', models.IntegerField(default=None, null=True)),
                ('entire_private_or_shared', models.CharField(max_length=20, null=True)),
                ('highest_guest_no', models.IntegerField(default=None, null=True)),
                ('beds', models.IntegerField(default=None, null=True)),
                ('bedrooms', models.IntegerField(default=None, null=True)),
                ('bathrooms', models.IntegerField(default=None, null=True)),
                ('private_bathroom_available', models.IntegerField(default=None, null=True)),
                ('need_host_confirmation', models.BooleanField(default=False)),
                ('partial_pay_allowed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.category')),
            ],
        ),
    ]
