# Generated by Django 4.0.1 on 2022-02-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(default=None, max_length=45, null=True)),
                ('facility_type', models.CharField(default=None, max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosting.category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='entire_private_or_shared',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
