# Generated by Django 4.0.1 on 2022-02-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_hosting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
