# Generated by Django 4.0.1 on 2022-02-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_facility_alter_property_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.facility')),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.hosting')),
            ],
        ),
    ]
