# Generated by Django 4.0.1 on 2022-02-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_rename_categories_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perNightCost', models.IntegerField(default=None)),
                ('entirePrivateOrShared', models.CharField(default=None, max_length=20, null=True)),
                ('highestGuestNo', models.IntegerField(default=None)),
                ('beds', models.IntegerField(default=None)),
                ('bedrooms', models.IntegerField(default=None)),
                ('bathrooms', models.IntegerField(default=None)),
                ('privateBathroomAvailable', models.IntegerField(default=None)),
                ('needHostConfirmation', models.BooleanField(default=False)),
                ('partialPayAllowed', models.BooleanField(default=False)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.category')),
                ('hostingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.hosting')),
            ],
        ),
    ]
