# Generated by Django 4.0.1 on 2022-02-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosting',
            old_name='hosting',
            new_name='hostingId',
        ),
    ]
