# Generated by Django 4.0.1 on 2022-02-18 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_photoupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoupload',
            name='title',
        ),
    ]
